[package]
name = "wirken-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wirken"
path = "src/main.rs"

[dependencies]
wirken-vault = { path = "../vault" }
wirken-audit = { path = "../audit" }
wirken-gateway = { path = "../gateway" }
wirken-agent = { path = "../agent" }
wirken-ipc = { path = "../ipc" }
wirken-mcp-proxy = { path = "../mcp-proxy" }
wirken-adapter-telegram = { path = "../adapter-telegram" }
wirken-adapter-discord = { path = "../adapter-discord" }
wirken-adapter-slack = { path = "../adapter-slack" }
wirken-adapter-teams = { path = "../adapter-teams" }
wirken-adapter-matrix = { path = "../adapter-matrix" }
wirken-adapter-whatsapp = { path = "../adapter-whatsapp" }
wirken-adapter-signal = { path = "../adapter-signal" }
wirken-adapter-google-chat = { path = "../adapter-google-chat" }
wirken-adapter-imessage = { path = "../adapter-imessage" }
capnp = { workspace = true }
ed25519-dalek = { workspace = true }
reqwest = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
console = "0.16"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
openssl = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
