@0xb9a0e7d3c1f24680;

# Wirken IPC Protocol
#
# This schema defines the wire format between the gateway core and
# adapter processes. All communication goes over Unix domain sockets
# using Cap'n Proto serialization.
#
# Schema evolution: new fields can be added to any struct without
# breaking existing adapters. Fields must never be removed or reordered.

# --- Authentication ---

struct AuthChallenge {
  nonce @0 :Data;
  # 32-byte random nonce generated by the gateway.
  # The adapter must sign this with its Ed25519 private key.
}

struct AuthResponse {
  publicKey @0 :Data;
  # 32-byte Ed25519 public key of the adapter.
  signature @1 :Data;
  # 64-byte Ed25519 signature of the challenge nonce.
  adapterId @2 :Text;
  # Identifier for this adapter (e.g., "telegram", "discord").
}

struct AuthResult {
  accepted @0 :Bool;
  reason @1 :Text;
  # Human-readable reason if rejected.
}

# --- Heartbeat ---

struct Heartbeat {
  seq @0 :UInt64;
  # Monotonically increasing sequence number.
}

# --- Messages ---

struct InboundMessage {
  # Message from a channel user, delivered by an adapter to the gateway.
  id @0 :Text;
  # Unique message ID (adapter-assigned).
  senderId @1 :Text;
  # Sender identifier (platform-specific: phone number, user ID, etc.).
  senderName @2 :Text;
  # Display name of the sender.
  channel @3 :Text;
  # Channel identifier (e.g., "telegram", "discord").
  conversationId @4 :Text;
  # Conversation/chat/group ID.
  text @5 :Text;
  # Message text content.
  timestamp @6 :Int64;
  # Unix timestamp in milliseconds.
  isGroup @7 :Bool;
  # Whether this message is from a group conversation.
  replyToId @8 :Text;
  # ID of the message this is replying to (empty if not a reply).
  metadata @9 :Text;
  # JSON-encoded platform-specific metadata.
}

struct OutboundMessage {
  # Message from the gateway to be sent by an adapter.
  conversationId @0 :Text;
  # Target conversation/chat/group ID.
  text @1 :Text;
  # Message text content.
  replyToId @2 :Text;
  # ID of the message to reply to (empty for new message).
  metadata @3 :Text;
  # JSON-encoded platform-specific metadata.
}

struct OutboundResult {
  # Result of sending an outbound message.
  success @0 :Bool;
  messageId @1 :Text;
  # Platform-assigned message ID if successful.
  error @2 :Text;
  # Error description if failed.
}

# --- Session ---

struct SessionQuery {
  sessionId @0 :Text;
}

struct SessionView {
  sessionId @0 :Text;
  channel @1 :Text;
  conversationId @2 :Text;
  messageCount @3 :UInt64;
  lastActivityMs @4 :Int64;
  # Unix timestamp in milliseconds of last activity.
}

# --- LLM streaming ---

struct LlmChunk {
  union {
    data @0 :Text;
    # A chunk of streaming LLM response text.
    error @1 :Text;
    # An error that terminated the stream.
    done @2 :Void;
    # Signal that the stream is complete.
  }
}

# --- Top-level frame ---
#
# Every message on the wire is a Frame. The tag determines
# which adapter/gateway handler processes it.

struct Frame {
  union {
    # Auth handshake (gateway → adapter, adapter → gateway)
    authChallenge @0 :AuthChallenge;
    authResponse @1 :AuthResponse;
    authResult @2 :AuthResult;

    # Keepalive
    heartbeat @3 :Heartbeat;

    # Adapter → Gateway
    inbound @4 :InboundMessage;
    sessionQuery @5 :SessionQuery;

    # Gateway → Adapter
    outbound @6 :OutboundMessage;
    outboundResult @7 :OutboundResult;
    sessionView @8 :SessionView;

    # LLM streaming (gateway → agent, bidirectional)
    llmChunk @9 :LlmChunk;
  }
}
