@0xb9a0e7d3c1f24680;

# Wirken IPC Protocol
#
# This schema defines the wire format between the gateway core and
# adapter processes. All communication goes over Unix domain sockets
# using Cap'n Proto serialization.
#
# Schema evolution: new fields can be added to any struct without
# breaking existing adapters. Fields must never be removed or reordered.

# --- Authentication ---

struct AuthChallenge {
  nonce @0 :Data;
  # 32-byte random nonce generated by the gateway.
  # The adapter must sign this with its Ed25519 private key.
}

struct AuthResponse {
  publicKey @0 :Data;
  # 32-byte Ed25519 public key of the adapter.
  signature @1 :Data;
  # 64-byte Ed25519 signature of the challenge nonce.
  adapterId @2 :Text;
  # Identifier for this adapter (e.g., "telegram", "discord").
}

struct AuthResult {
  accepted @0 :Bool;
  reason @1 :Text;
  # Human-readable reason if rejected.
}

# --- Heartbeat ---

struct Heartbeat {
  seq @0 :UInt64;
  # Monotonically increasing sequence number.
}

# --- Messages ---

struct InboundMessage {
  # Message from a channel user, delivered by an adapter to the gateway.
  id @0 :Text;
  # Unique message ID (adapter-assigned).
  senderId @1 :Text;
  # Sender identifier (platform-specific: phone number, user ID, etc.).
  senderName @2 :Text;
  # Display name of the sender.
  channel @3 :Text;
  # Channel identifier (e.g., "telegram", "discord").
  conversationId @4 :Text;
  # Conversation/chat/group ID.
  text @5 :Text;
  # Message text content.
  timestamp @6 :Int64;
  # Unix timestamp in milliseconds.
  isGroup @7 :Bool;
  # Whether this message is from a group conversation.
  replyToId @8 :Text;
  # ID of the message this is replying to (empty if not a reply).
  metadata @9 :Text;
  # JSON-encoded platform-specific metadata.
}

struct OutboundMessage {
  # Message from the gateway to be sent by an adapter.
  conversationId @0 :Text;
  # Target conversation/chat/group ID.
  text @1 :Text;
  # Message text content.
  replyToId @2 :Text;
  # ID of the message to reply to (empty for new message).
  metadata @3 :Text;
  # JSON-encoded platform-specific metadata.
}

struct OutboundResult {
  # Result of sending an outbound message.
  success @0 :Bool;
  messageId @1 :Text;
  # Platform-assigned message ID if successful.
  error @2 :Text;
  # Error description if failed.
}

# --- Session ---

struct SessionQuery {
  sessionId @0 :Text;
}

struct SessionView {
  sessionId @0 :Text;
  channel @1 :Text;
  conversationId @2 :Text;
  messageCount @3 :UInt64;
  lastActivityMs @4 :Int64;
  # Unix timestamp in milliseconds of last activity.
}

# --- LLM streaming ---

struct LlmChunk {
  union {
    data @0 :Text;
    # A chunk of streaming LLM response text.
    error @1 :Text;
    # An error that terminated the stream.
    done @2 :Void;
    # Signal that the stream is complete.
  }
}

# --- Hooks ---
#
# Hook handshake reuses the same Ed25519 wire shape as the adapter
# handshake but binds the signature under a distinct domain
# separator (see crates/ipc/src/auth.rs HOOK_HANDSHAKE_DOMAIN) so an
# adapter signature can never replay against the hook acceptor and
# vice versa. The wire-level structs are separate so the gateway can
# route an inbound connection by which response variant the peer
# sent first.

struct HookAuthResponse {
  publicKey @0 :Data;
  # 32-byte Ed25519 public key of the hook process.
  signature @1 :Data;
  # 64-byte Ed25519 signature of the challenge nonce.
  hookId @2 :Text;
  # Identifier for this hook (e.g., "policy-eval", "ralph-loop").
  hookType @3 :Text;
  # "observe" or "veto". The gateway routes the post-handshake
  # connection by this label; an unknown label is a handshake reject.
}

struct SessionLogTail {
  # Hook → Gateway. Observe-hook pull request for events with
  # sequence >= sinceSeq for the named session.
  sessionId @0 :Text;
  sinceSeq @1 :UInt64;
  # Caller-supplied cursor. Hook advances on its own after each
  # successful response.
  maxRows @2 :UInt32;
  # Soft cap on the response size so a hook coming back from a long
  # downtime does not get an unboundedly large batch.
}

struct SessionLogTailEvent {
  seq @0 :UInt64;
  # Per-session monotonic sequence number, copied from the session
  # log so the hook's cursor advances against the same numbers the
  # gateway sees.
  payload @1 :Text;
  # JSON-serialized SessionEvent. The hook deserializes against its
  # own copy of the SessionEvent enum; the JSON wire keeps the
  # capnp schema independent of audit-side variant churn.
}

struct SessionLogTailResponse {
  # Gateway → Hook. Batch response to a SessionLogTail.
  events @0 :List(SessionLogTailEvent);
  nextSeq @1 :UInt64;
  # The sequence the hook should pass as `sinceSeq` on the next
  # SessionLogTail to receive only newer rows. If `events` is empty
  # this equals the request's `sinceSeq`.
}

struct VetoRequest {
  # Gateway → Veto hook. Pre-dispatch tool call. The hook responds
  # with a VetoResponse keyed by requestId.
  #
  # Intentionally narrow: tool name, arguments, and the session that
  # surrounds the call. Per-call agent identity is not on the wire;
  # routing must remain handshake-derived (see
  # tests/no_payload_routing.rs). The gateway logs the local agent
  # id onto the SessionEvent::HookDispatched row at dispatch time,
  # so the audit chain still carries the attribution even though the
  # hook never sees an agent_id field.
  requestId @0 :Text;
  toolName @1 :Text;
  arguments @2 :Text;
  # JSON-encoded tool arguments, as the agent received them from the
  # LLM and after Wirken's per-skill / tier permission gate already
  # passed.
  sessionId @3 :Text;
}

struct VetoResponse {
  requestId @0 :Text;
  union {
    allow @1 :Void;
    deny @2 :Text;
    # Operator-readable reason. Recorded on the audit chain and
    # surfaced as the tool call's failure message.
  }
}

# --- Top-level frame ---
#
# Every message on the wire is a Frame. The tag determines
# which adapter/gateway handler processes it.

struct Frame {
  union {
    # Auth handshake (gateway → adapter, adapter → gateway)
    authChallenge @0 :AuthChallenge;
    authResponse @1 :AuthResponse;
    authResult @2 :AuthResult;

    # Keepalive
    heartbeat @3 :Heartbeat;

    # Adapter → Gateway
    inbound @4 :InboundMessage;
    sessionQuery @5 :SessionQuery;

    # Gateway → Adapter
    outbound @6 :OutboundMessage;
    outboundResult @7 :OutboundResult;
    sessionView @8 :SessionView;

    # LLM streaming (gateway → agent, bidirectional)
    llmChunk @9 :LlmChunk;

    # Hook handshake. authChallenge / authResult are reused; the
    # response shape is distinct so the gateway routes by which
    # response variant the peer sent.
    hookAuthResponse @10 :HookAuthResponse;

    # Observe-hook pull cursor (hook → gateway, gateway → hook).
    sessionLogTail @11 :SessionLogTail;
    sessionLogTailResponse @12 :SessionLogTailResponse;

    # Veto-hook synchronous request/response.
    vetoRequest @13 :VetoRequest;
    vetoResponse @14 :VetoResponse;
  }
}
